{% set name = "result" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/result-{{ version }}.tar.gz
  sha256: c48c909e92181a075ba358228a3fe161e26d205dad416ad81f27f23515a5626d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - result
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rustedpy/result
  summary: A Rust-like result type for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
